# Pandas exercises

## Import pandas

* Import pandas and numpy with the standard shorthand aliases pd and np, respectively

In [28]:
import pandas as pd
import numpy as np

## Creating pandas objects

* Create a pandas Series object with keys corresponding to the days of the week (ex., "Mon", "Tue", Wed" "Thu", "Fri", "Sat", "Sun") and values corresponding to the integer numbers from 0 to 6.

In [29]:
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
values = [0, 1, 2, 3, 4, 5, 6]
week_series = pd.Series(values, days)
week_series

Mon    0
Tue    1
Wed    2
Thu    3
Fri    4
Sat    5
Sun    6
dtype: int64

* Create a pandas DataFrame with 5 columns and 10 rows containing random numbers from the standard Gaussian distribution. Assign column names "C0", "C1", "C2", "C3", "C4". Do not specify row names.

In [30]:
data = np.random.randn(10,5)
columns = ["C0", "C1", "C2", "C3", "C4"]
df = pd.DataFrame(data, columns=columns)
df

         C0        C1        C2        C3        C4
0 -0.526348  0.148511 -0.938707 -1.117272 -0.116585
1  0.249980  1.045642  0.651406 -0.477010 -2.374596
2 -0.176203  0.188500 -1.091333 -0.161747  0.319296
3  0.035652 -0.365163 -0.807888  0.963172  0.768308
4  1.204059  0.060452  0.913240 -1.915954  0.342392
5 -0.615811 -2.058036 -1.564101 -1.481222 -1.261355
6 -0.607566  0.820530 -1.848295 -0.482428  0.302309
7  0.619123  0.370378 -1.189866 -0.723973  1.000184
8  1.289208  1.029391 -0.520438  1.245518 -0.846681
9  0.027585  0.161611 -1.227854  0.330104  0.305261

* Create a pandas DataFrame with 5 columns and 10 rows containing random numbers from the standard Gaussian distribution. Assign column names "C0", "C1", "C2", "C3", "C4" and row names "R0", "R1", "R2", ..., "R9".

In [31]:
data = np.random.randn(10,5)
columns = ["C0", "C1", "C2", "C3", "C4"]
rows = ["R0", "R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9"]
df = pd.DataFrame(data, rows, columns)
df

          C0        C1        C2        C3        C4
R0 -0.833667  0.003482  0.449786  1.160967  1.261711
R1  1.042507  1.636257 -0.386512  0.314857 -0.593852
R2 -0.636286  1.059351  1.715232 -1.172888 -0.281124
R3  0.334860  0.390764  1.114713 -0.143094  0.074275
R4  0.311925 -1.261532 -0.852115 -1.090793 -0.010340
R5 -1.220606 -0.292852 -0.702823  0.063174  0.480627
R6  1.387122 -0.816169  0.959289 -0.016832  0.506152
R7  0.038607  0.286173 -1.228324 -0.266520  0.329172
R8  1.229059  1.156810  1.846300  0.133917 -0.539655
R9  0.452398  1.151173  1.870925  0.863566 -0.290058

* Read the csv file "worldcities.csv" into a pandas DataFrame. Assign it to a variable with name ``df_cities``.

In [32]:
df_cities = pd.read_csv('worldcities.csv')

* Display the first 3 rows and the last 3 rows of ``df_cities``.

In [33]:
df_cities.head(3)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881

In [34]:
df_cities.tail(3)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
15490,Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
15491,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
15492,Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

## Indexing and slicing

* Create a pandas DataFrame containing only the columns "city", "lat", "lng" of ``df_cities``

In [35]:
df_cities[["city", "lat", "lng"]]

              city      lat       lng
0            Tokyo  35.6850  139.7514
1         New York  40.6943  -73.9249
2      Mexico City  19.4424  -99.1310
3           Mumbai  19.0170   72.8570
4        São Paulo -23.5587  -46.6250
...            ...      ...       ...
15488  Timmiarmiut  62.5333  -42.2167
15489  Cheremoshna  51.3894   30.0989
15490    Ambarchik  69.6510  162.3336
15491      Nordvik  74.0165  111.5100
15492      Ennadai  61.1333 -100.8833

[15493 rows x 3 columns]

* Create a pandas Series containing the column "city" of ``df_cities``

In [36]:
panda_cities = pd.Series(df_cities["city"])
panda_cities

0              Tokyo
1           New York
2        Mexico City
3             Mumbai
4          São Paulo
            ...
15488    Timmiarmiut
15489    Cheremoshna
15490      Ambarchik
15491        Nordvik
15492        Ennadai
Name: city, Length: 15493, dtype: object

* What is the difference between ``df_cities["city"]`` and ``df_cities[["city"]]``?

In [37]:
type(df_cities["city"])

pandas.core.series.Series

In [38]:
type(df_cities[["city"]])

pandas.core.frame.DataFrame

* Set the column ``city_ascii`` as row index of the dataframe ``df_cities``

In [39]:
df_cities = df_cities.set_index("city_ascii")
df_cities

,city,lat,lng,country,iso2,iso3,admin_name,capital,population,id
city_ascii,,,,,,,,,,
Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
Sao Paulo,São Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...
Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

* Select the row of ``df_cities`` with the data of Lugano using the `.loc` indexer

In [43]:
lugano_data = df_cities.loc["Lugano"]
lugano_data

city               Lugano
lat               46.0004
lng                8.9667
country       Switzerland
iso2                   CH
iso3                  CHE
admin_name         Ticino
capital               NaN
population       105388.0
id             1756503816
Name: Lugano, dtype: object

* Select the first 3 rows and the last 3 columns of ``df_cities``

In [44]:
df_cities.iloc[:3, -3:]

             capital  population          id
city_ascii
Tokyo        primary  35676000.0  1392685764
New York         NaN  19354922.0  1840034016
Mexico City  primary  19028000.0  1484247881

## Boolean indexing

* Read again the csv file "worldcities.csv" into a pandas DataFrame. Assign it to a variable with name ``df_cities``.

In [74]:
df_cities = pd.read_csv('worldcities.csv')

* Find the latitude of Lugano (city_ascii == 'Lugano') and assign it to the variable ``lat_lugano``.

In [83]:
lat_lugano = df_cities.loc[df_cities['city_ascii'] == 'Lugano', 'lat']
float(lat_lugano.values[0])

* Select all the cities at the north of Lugano (latitude > ``lat_lugano``)

In [72]:
df_cities_nord_lugano = df_cities.loc[df_cities['lat'] > lat_lugano]
df_cities_nord_lugano

,city,lat,lng,country,iso2,iso3,admin_name,capital,population,id
city_ascii,,,,,,,,,,
Moscow,Moscow,55.7522,37.6155,Russia,RU,RUS,Moskva,primary,10452000.0,1643318494
Paris,Paris,48.8667,2.3333,France,FR,FRA,Île-de-France,primary,9904000.0,1250015082
London,London,51.5000,-0.1167,United Kingdom,GB,GBR,"London, City of",primary,8567000.0,1826645935
Saint Petersburg,Saint Petersburg,59.9390,30.3160,Russia,RU,RUS,Sankt-Peterburg,admin,4553000.0,1643616350
Seattle,Seattle,47.6211,-122.3244,United States,US,USA,Washington,NaN,3643765.0,1840021117
...,...,...,...,...,...,...,...,...,...,...
Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423


* Select all cities at the north of Lugano in Italy (country == 'Italy')

In [91]:
df_cities_north_Lugano_in_Italy = df_cities.loc[(df_cities['lat'] > lat_lugano) & (df_cities['country'] == "Italy")]
df_cities_north_Lugano_in_Italy

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
2936,Udine,Udine,46.0700,13.24,Italy,IT,ITA,Friuli-Venezia Giulia,minor,119009.0,1380396446
3122,Trento,Trento,46.0804,11.12,Italy,IT,ITA,Trentino-Alto Adige,admin,107808.0,1380953307
7068,Bolzano,Bolzano,46.5004,11.36,Italy,IT,ITA,Trentino-Alto Adige,minor,95895.0,1380677819