# Pandas exercises

## Import pandas

* Import pandas and numpy with the standard shorthand aliases pd and np, respectively

In [94]:
import pandas as pd
import numpy as np

## Creating pandas objects

* Create a pandas Series object with keys corresponding to the days of the week (ex., "Mon", "Tue", Wed" "Thu", "Fri", "Sat", "Sun") and values corresponding to the integer numbers from 0 to 6.

In [95]:
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
values = [0, 1, 2, 3, 4, 5, 6]
week_series = pd.Series(values, days)
week_series

Mon    0
Tue    1
Wed    2
Thu    3
Fri    4
Sat    5
Sun    6
dtype: int64

* Create a pandas DataFrame with 5 columns and 10 rows containing random numbers from the standard Gaussian distribution. Assign column names "C0", "C1", "C2", "C3", "C4". Do not specify row names.

In [96]:
data = np.random.randn(10,5)
columns = ["C0", "C1", "C2", "C3", "C4"]
df = pd.DataFrame(data, columns=columns)
df

         C0        C1        C2        C3        C4
0  1.190907  0.058303  0.865955 -0.286885 -0.225021
1 -0.559908  1.711990  1.796116 -0.085221 -1.320228
2  0.936848 -2.457554  0.419697  1.220973 -0.347256
3 -0.734798 -0.748834 -0.032280 -1.295965  1.171101
4  0.877608 -2.717156 -1.666821  1.033776  0.859635
5 -0.311027  0.770220  1.129197  0.020292  0.535935
6 -0.769297  1.660339 -0.497191  1.244695  0.224983
7 -0.189186  0.289178  0.065375 -0.529087 -0.230130
8  0.718257  0.296788  1.068650 -0.185731 -0.680869
9 -0.520143  1.019729 -2.841986  1.499190  1.359605

* Create a pandas DataFrame with 5 columns and 10 rows containing random numbers from the standard Gaussian distribution. Assign column names "C0", "C1", "C2", "C3", "C4" and row names "R0", "R1", "R2", ..., "R9".

In [97]:
data = np.random.randn(10,5)
columns = ["C0", "C1", "C2", "C3", "C4"]
rows = ["R0", "R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9"]
df = pd.DataFrame(data, rows, columns)
df

          C0        C1        C2        C3        C4
R0 -0.374901  0.129475  0.698228 -1.908583  0.625530
R1 -0.706447  0.707870  2.397000 -1.202657  1.349255
R2 -1.309351  1.470375  0.460603 -1.100508 -0.305214
R3 -0.681541 -0.613985 -0.246129 -0.704224 -0.013630
R4  0.435309  0.337747 -0.031614  1.401310 -0.180368
R5 -1.343621  1.459789  0.492181 -0.917898  0.584497
R6  0.816848 -1.606584  0.140534 -0.645616  0.273063
R7  0.443838 -0.082364 -0.709301 -0.034014 -0.783500
R8  1.338905  0.617226  0.384572  0.590117  0.702457
R9  1.022337 -0.567980 -0.619512  1.415739 -0.866631

* Read the csv file "worldcities.csv" into a pandas DataFrame. Assign it to a variable with name ``df_cities``.

In [98]:
df_cities = pd.read_csv('worldcities.csv')

* Display the first 3 rows and the last 3 rows of ``df_cities``.

In [99]:
df_cities.head(3)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
1,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
2,Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881

In [100]:
df_cities.tail(3)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
15490,Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
15491,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
15492,Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

## Indexing and slicing

* Create a pandas DataFrame containing only the columns "city", "lat", "lng" of ``df_cities``

In [101]:
df_cities[["city", "lat", "lng"]]

              city      lat       lng
0            Tokyo  35.6850  139.7514
1         New York  40.6943  -73.9249
2      Mexico City  19.4424  -99.1310
3           Mumbai  19.0170   72.8570
4        São Paulo -23.5587  -46.6250
...            ...      ...       ...
15488  Timmiarmiut  62.5333  -42.2167
15489  Cheremoshna  51.3894   30.0989
15490    Ambarchik  69.6510  162.3336
15491      Nordvik  74.0165  111.5100
15492      Ennadai  61.1333 -100.8833

[15493 rows x 3 columns]

* Create a pandas Series containing the column "city" of ``df_cities``

In [102]:
panda_cities = pd.Series(df_cities["city"])
panda_cities

0              Tokyo
1           New York
2        Mexico City
3             Mumbai
4          São Paulo
            ...
15488    Timmiarmiut
15489    Cheremoshna
15490      Ambarchik
15491        Nordvik
15492        Ennadai
Name: city, Length: 15493, dtype: object

* What is the difference between ``df_cities["city"]`` and ``df_cities[["city"]]``?

In [103]:
type(df_cities["city"])

pandas.core.series.Series

In [104]:
type(df_cities[["city"]])

pandas.core.frame.DataFrame

* Set the column ``city_ascii`` as row index of the dataframe ``df_cities``

In [105]:
df_cities = df_cities.set_index("city_ascii")
df_cities

,city,lat,lng,country,iso2,iso3,admin_name,capital,population,id
city_ascii,,,,,,,,,,
Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,35676000.0,1392685764
New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19354922.0,1840034016
Mexico City,Mexico City,19.4424,-99.1310,Mexico,MX,MEX,Ciudad de México,primary,19028000.0,1484247881
Mumbai,Mumbai,19.0170,72.8570,India,IN,IND,Mahārāshtra,admin,18978000.0,1356226629
Sao Paulo,São Paulo,-23.5587,-46.6250,Brazil,BR,BRA,São Paulo,admin,18845000.0,1076532519
...,...,...,...,...,...,...,...,...,...,...
Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423

* Select the row of ``df_cities`` with the data of Lugano using the `.loc` indexer

In [106]:
lugano_data = df_cities.loc["Lugano"]
lugano_data

city               Lugano
lat               46.0004
lng                8.9667
country       Switzerland
iso2                   CH
iso3                  CHE
admin_name         Ticino
capital               NaN
population       105388.0
id             1756503816
Name: Lugano, dtype: object

* Select the first 3 rows and the last 3 columns of ``df_cities``

In [107]:
df_cities.iloc[:3, -3:]

             capital  population          id
city_ascii
Tokyo        primary  35676000.0  1392685764
New York         NaN  19354922.0  1840034016
Mexico City  primary  19028000.0  1484247881

## Boolean indexing

* Read again the csv file "worldcities.csv" into a pandas DataFrame. Assign it to a variable with name ``df_cities``.

In [108]:
df_cities = pd.read_csv('worldcities.csv')

* Find the latitude of Lugano (city_ascii == 'Lugano') and assign it to the variable ``lat_lugano``.

In [120]:
lat_lugano = df_cities.loc[df_cities['city_ascii'] == 'Lugano', 'lat']
lat_lugano.iloc[0]

np.float64(46.0004)

* Select all the cities at the north of Lugano (latitude > ``lat_lugano``)

In [117]:
df_cities_nord_lugano = df_cities.loc[df_cities['lat'] > lat_lugano]
df_cities_nord_lugano

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
17,Moscow,Moscow,55.7522,37.6155,Russia,RU,RUS,Moskva,primary,10452000.0,1643318494
19,Paris,Paris,48.8667,2.3333,France,FR,FRA,Île-de-France,primary,9904000.0,1250015082
25,London,London,51.5000,-0.1167,United Kingdom,GB,GBR,"London, City of",primary,8567000.0,1826645935
63,Saint Petersburg,Saint Petersburg,59.9390,30.3160,Russia,RU,RUS,Sankt-Peterburg,admin,4553000.0,1643616350
87,Seattle,Seattle,47.6211,-122.3244,United States,US,USA,Washington,NaN,3643765.0,1840021117
...,...,...,...,...,...,...,...,...,...,...,...
15488,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
15489,Cheremoshna,Cheremoshna,51.3894,30.0989,Ukraine,UA,UKR,Kyyivs’ka Oblast’,NaN,0.0,1804043438
15490,Ambarchik,Ambarchik,69.6510,162.3336,Russia,RU,RUS,Sakha (Yakutiya),NaN,0.0,1643739159
15491,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468
15492,Ennadai,Ennadai,61.1333,-100.8833,Canada,CA,CAN,Nunavut,NaN,0.0,1124019423


* Select all cities at the north of Lugano in Italy (country == 'Italy')

In [118]:
df_cities_north_Lugano_in_Italy = df_cities.loc[(df_cities['lat'] > lat_lugano) & (df_cities['country'] == "Italy")]
df_cities_north_Lugano_in_Italy

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
2936,Udine,Udine,46.0700,13.24,Italy,IT,ITA,Friuli-Venezia Giulia,minor,119009.0,1380396446
3122,Trento,Trento,46.0804,11.12,Italy,IT,ITA,Trentino-Alto Adige,admin,107808.0,1380953307
7068,Bolzano,Bolzano,46.5004,11.36,Italy,IT,ITA,Trentino-Alto Adige,minor,95895.0,1380677819